In [ ]:
import sys

In [ ]:
sys.path.append(r"/home/gpaul/Scripts/Maru.Materials/src")

In [ ]:
import materials

In [ ]:
borosilicate = materials.Borosilicate_glass()

In [ ]:
borosilicate.thermalconductivity()[0].head()

       T(K)  lambda(W/mK)
0  0.080682      0.000122
1  0.092242      0.000164
2  0.102364      0.000204
3  0.117015      0.000258
4  0.133772      0.000336

In [ ]:
borosilicate.thermalconductivity()[1].head()

       T(K)  lambda(W/mK)
0  0.039650      0.000030
1  0.060881      0.000067
2  0.090908      0.000156
3  0.147517      0.000402
4  0.194516      0.000702

In [ ]:
borosilicate.cte().head()

       T(K)  CTE(1/K)
0  3.969539 -0.000015
1  5.812121 -0.000015
2  7.218021 -0.000016
3  8.097241 -0.000016
4  8.888060 -0.000017

In [ ]:
fusedsilica = materials.Fusedsilica_glass()

In [ ]:
fusedsilica.thermalconductivity()

FileNotFoundError: [Errno 2] No such file or directory: '/home/gpaul/Scripts/Maru.Materials/src/materials/database/src/materials/database/fusedsilica_lambda_White1997.csv'