In [14]:
import sys

In [15]:
sys.path.append(r"/home/gpaul/Scripts/Maru.Materials/src")

In [16]:
import materials

In [17]:
glass = materials.Glass()

In [18]:
glass.thermalconductivity()[0].head()

   temperature(K)  value(W/mK)
0        0.080682     0.000122
1        0.092242     0.000164
2        0.102364     0.000204
3        0.117015     0.000258
4        0.133772     0.000336

In [19]:
glass.thermalconductivity()[1].head()

   temperature(K)  value(W/mK)
0        0.039650     0.000030
1        0.060881     0.000067
2        0.090908     0.000156
3        0.147517     0.000402
4        0.194516     0.000702